# SPDX-FileCopyrightText: 2026 Julian Malinowski
# SPDX-License-Identifier: CC0-1.0

[build-system]
    build-backend = "uv_build"
    requires = ["uv_build>=0.12.6,<0.13"]


[project]
    authors = [ { name = "Julian Malinowski" } ]
    classifiers = [
        "Development Status :: 5 - Production/Stable",
        "Intended Audience :: End Users/Desktop",
        "Natural Language :: English",
        "Operating System :: POSIX :: Linux",
        "Operating System :: Microsoft :: Windows",
        "Programming Language :: Python :: 3 :: Only",
    ]
    description = "A Python program to generate passwords."
    license-files = [ "LICENSES/*.txt" ]
    maintainers = [ { name = "kiichigo" } ]
    name = "kiurui"
    requires-python = ">=3.11"
    version = "1.0.0"


[project.optional-dependencies]
    dev = [
        "groundwork-sphinx-theme",
        "pre-commit",
        "reuse",
        "ruff",
        "sphinx"
    ]


[project.urls]
    Issues = "https://codeberg.org/kiichigo/kiurui/issues"
    Repository = "https://codeberg.org/kiichigo/kiurui"


# Based on https://github.com/secureblue/secureblue/blob/live/pyproject.toml
[tool.ruff.lint]
    ignore = [
        "ANN204",   # missing-return-type-special-method
        "ANN401",   # any-type
        "S603",     # subprocess-without-shell-equals-true
    ]
    mccabe.max-complexity = 8
    select = [
        "A",    # flake8-builtins
        "ANN",  # flake8-annotations
        "ARG",  # flake8-unused-arguments
        "B",    # flake8-bugbear
        "C4",   # flake8-comprehensions
        "C90",  # mccabe
        "E",    # pycodestyle error
        "F",    # pyflakes
        "FIX",  # flake8-fixme
        "FURB", # refurb
        "I",    # isort
        "ICN",  # flake8-import-conventions
        "N",    # pep8-naming
        "PL",   # pylint
        "PIE",  # flake8-pie
        "Q",    # flake8-quotes
        "RET",  # flake8-return
        "RSE",  # flake8-raise
        "RUF",  # Ruff-specific rules
        "S",    # flake8-bandit
        "SIM",  # flake8-simplify
        "SLF",  # flake8-self
        "TC",   # flake8-type-checking
        "UP",   # pyupgrade
        "W",    # pycodestyle warning
    ]
