# SPDX-FileCopyrightText: 2020 Free Software Foundation Europe e.V.
# SPDX-License-Identifier: CC0-1.0
name: REUSE compliance check
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  test:
    runs-on: codeberg-tiny
    container: fsfe/reuse:latest
    steps:
      - run: |
          apk add nodejs          
      - uses: actions/checkout@v5
      - name: Verify REUSE compliance
        run: |
          reuse lint